name: Create Issue

on:
  schedule:
    - cron:'0 0 */3 *'

jobs:
  build:
    name: create Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
